apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: firdaaridzkii/kantin-backend:v1
          ports:
            - containerPort: 5000
          env:
            - name: NAMA_PRAKTIKAN
              value: "Firda Ridzki Utami"
            - name: NIM_PRAKTIKAN
              value: "2401626"
