pipeline {
    agent any

    environment {
        BACKEND_IMAGE = "firdaaridzkii/kantin-backend:v2"
        FRONTEND_IMAGE = "firdaaridzkii/kantin-frontend:v1"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/firda888-r/Praktikum-Cloud.git'
            }
        }

        stage('Build') {
            steps {
                sh '''
                docker build -t $BACKEND_IMAGE kantin-app/backend
                docker build -t $FRONTEND_IMAGE kantin-app/frontend
                '''
            }
        }

        stage('Push') {
            steps {
                sh '''
                docker push $BACKEND_IMAGE
                docker push $FRONTEND_IMAGE
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                kubectl apply -f kantin-app/k8s/backend-deployment.yaml
                kubectl apply -f kantin-app/k8s/backend-service.yaml
                kubectl apply -f kantin-app/k8s/frontend-deployment.yaml
                kubectl apply -f kantin-app/k8s/frontend-service.yaml
                kubectl apply -f kantin-app/k8s/ingress.yaml
                '''
            }
        }

    }
}